Merge "/Users/eliguli712/DataStructure/numerical_analysis/FEA_meg/applied_forces/tetwild_input_smoothed_comsol_watertight.stl";
sl[] = Surface "*";
Surface Loop(1) = {sl[]};
Volume(1) = {1};
Mesh.CharacteristicLengthMin = 0.9;
Mesh.CharacteristicLengthMax = 2.8;
Mesh.Algorithm3D = 1;
Mesh.ElementOrder = 1;
Mesh.Optimize = 1;
Mesh.OptimizeNetgen = 1;
General.NumThreads = 8;
Mesh 3;
Save "/Users/eliguli712/DataStructure/numerical_analysis/FEA_meg/applied_forces/tetwild_input_smoothed_comsol_tet_vol.msh";
